### ISSUE TITLE
No tags?

### ISSUE THREAD

**Issue by lrvl** [Deltares-research/FAIR-data-example-project#9]
How can this repo be reproducible without using Release Tags or the well-known https://semver.org/ ?

**Comment by JoerivanEngelen** [comment]
Thank you for your comment. 

First, it is good to clarify that these instructions are intended for projects, not products.  What we want to avoid is that people start to add tags after each tiny change. Things like: "v1, v2, v2_finally, v2_really_finally, v3" is what we are trying to avoid in the first place. I think adding a semver release tag would be appropriate at the end of the project, to store the final state. When work on a repository is continued later in a follow-up project, it would help switching between states. However, quite often projects are one-off and no changes to the repository are made after its finish, as no follow-up projects happen. In this case only a single version needs to be tagged and thus tagging is overkill. 

A project can also be reproducible if people have stored the exact git hash they did their model simulations with with their model output (next to the location of the git repo). I actually have colleagues who have done this: as they were constantly making fixes to their code base and creating new model results iteratively. This happens frequently in projects: You evaluate model results and then realize that the scripts creating model input require some changes running again, after which you either figure out you are closer to the right answer or you just made things worse and need to go back. In this process, I don't see a real usecase for release tags. After they have finally figured out the simulations which are contained in the final report, this git hash could be tagged to clarify that this is the state with which output was generated for the final report. Their output metadata also contains the git hash though, so a release tag is not necessary to make the project reproducbile. It certainly helps though.

I'll tag this repo at least and write some extra instructions how and when to tag a project.
